version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--enable-feature=remote-write-receiver'
    ports:
      - "9090:9090"
    networks:
      - otel-network

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=muzo
      - GF_SECURITY_ADMIN_PASSWORD=muzo
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/prometheus-datasource.yaml:/etc/grafana/provisioning/datasources/prometheus-datasource.yaml 
      - ./grafana/dashboard-provisioning.yaml:/etc/grafana/provisioning/dashboards/dashboard-provisioning.yaml 
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards 
    ports:
      - "3000:3000"
    networks:
      - otel-network

  otel-collector:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./otel-collector/config.yaml:/etc/otel-collector-config.yaml
    command:
      - '--config=/etc/otel-collector-config.yaml'
    ports:
      - "4317:4317"
      - "4318:4318"
      - "55678:55678"
      - "14250:14250"
      - "14268:14268"
      - "6831:6831"
      - "6832:6832"
      - "9411:9411"
      - "8888:8888"
      - "1777:1777"
      - "55679:55679"
    networks:
      - otel-network

networks:
  otel-network:
    driver: bridge


































